# Generated by Django 5.0.3 on 2024-04-16 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_post_body_alter_post_created_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid3, editable=False, unique=True),
        ),
    ]
