# Generated by Django 6.0.1 on 2026-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(choices=[('5m', '5 دقیقه'), ('30m', '30 دقیقه'), ('1h', '1 ساعت'), ('4h', '4 ساعت'), ('1d', '1 روز')], max_length=10)),
                ('prediction', models.CharField(choices=[('UP', 'صعودی'), ('DOWN', 'نزولی'), ('NEUTRAL', 'خنثی')], max_length=10)),
                ('confidence', models.FloatField()),
                ('technical_signal', models.CharField(choices=[('UP', 'صعودی'), ('DOWN', 'نزولی'), ('NEUTRAL', 'خنثی')], max_length=10)),
                ('ml_signal', models.CharField(choices=[('UP', 'صعودی'), ('DOWN', 'نزولی'), ('NEUTRAL', 'خنثی')], max_length=10)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیش\u200cبینی',
                'verbose_name_plural': 'پیش\u200cبینی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
