from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_index, name='index'),
    path('monitoring/', views.monitoring, name='monitoring'),
    path('users/', views.user_list, name='users'),
    path('users/<int:user_id>/ban/', views.user_toggle_ban, name='user_ban'),
    path('users/<int:user_id>/verify/', views.user_toggle_verified, name='user_verify'),
    path('users/<int:user_id>/', views.user_detail, name='user_detail'),
    path('posts/', views.post_list, name='posts'),
    path('posts/bulk-delete/', views.post_bulk_delete, name='post_bulk_delete'),
    path('posts/<int:pk>/approve/', views.post_approve, name='post_approve'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('notify/', views.notify_center, name='notify'),
    path('api/user-search/', views.user_search_api, name='user_search_api'),
    path('comments/', views.comment_list, name='comments'),
    path('comments/bulk-delete/', views.comment_bulk_delete, name='comment_bulk_delete'),
    path('comments/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comments/<int:pk>/reject/', views.comment_reject, name='comment_reject'),
    path('comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('hashtags/', views.hashtag_list, name='hashtags'),
    path('hashtags/<int:pk>/approve/', views.hashtag_approve, name='hashtag_approve'),
    path('hashtags/<int:hashtag_id>/delete/', views.hashtag_delete, name='hashtag_delete'),
    path('games/', views.game_list, name='games'),
    path('games/add/', views.game_add, name='game_add'),
    path('games/<int:game_id>/edit/', views.game_edit, name='game_edit'),
    path('games/<int:game_id>/delete/', views.game_delete, name='game_delete'),
    path('games/<int:game_id>/toggle-active/', views.game_toggle_active, name='game_toggle_active'),
    path('games/<int:game_id>/toggle-online/', views.game_toggle_online, name='game_toggle_online'),
    path('score-settings/', views.score_settings_view, name='score_settings'),
    path('zarban/', views.zarban_list, name='zarban'),
    path('zarban/<int:user_id>/manage/', views.zarban_manage, name='zarban_manage'),
    # گردونه شانس
    path('spin/', views.spin_wheel_list, name='spin_wheels'),
    path('spin/add/', views.spin_wheel_add, name='spin_wheel_add'),
    path('spin/<int:wheel_id>/edit/', views.spin_wheel_edit, name='spin_wheel_edit'),
    path('spin/<int:wheel_id>/delete/', views.spin_wheel_delete, name='spin_wheel_delete'),
    path('spin/<int:wheel_id>/toggle/', views.spin_wheel_toggle, name='spin_wheel_toggle'),
    path('spin/<int:wheel_id>/items/', views.spin_wheel_items, name='spin_wheel_items'),
    # ماموریت‌های روزانه
    path('missions/', views.daily_mission_list, name='daily_missions'),
    path('missions/day/add/', views.mission_day_add, name='mission_day_add'),
    path('missions/day/<int:day_id>/', views.mission_day_edit, name='mission_day_edit'),
    path('missions/day/<int:day_id>/delete/', views.mission_day_delete, name='mission_day_delete'),
    path('missions/day/<int:day_id>/toggle/', views.mission_day_toggle, name='mission_day_toggle'),
    path('missions/save/', views.mission_save, name='mission_save'),
    path('spin/upload-icon/', views.upload_spin_icon, name='spin_upload_icon'),
    # پریمیوم
    path('premium/', views.premium_index, name='premium'),
    path('premium/plan/save/', views.premium_plan_save, name='premium_plan_save'),
    path('premium/plan/<int:plan_id>/delete/', views.premium_plan_delete, name='premium_plan_delete'),
    path('premium/assign/', views.premium_assign, name='premium_assign'),
    path('premium/<int:sub_id>/revoke/', views.premium_revoke, name='premium_revoke'),
    path('premium/adjust-days/', views.premium_adjust_days, name='premium_adjust_days'),
]
