# Generated by Django 6.0.5 on 2026-05-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_post', 'اولین پست'), ('first_follow', 'اولین فالو'), ('popular_post', 'پست پرلایک'), ('veteran', 'کهنه\u200cکار'), ('social', 'اجتماعی'), ('tournament_win', 'برنده تورنمنت'), ('custom', 'سفارشی')], max_length=20, verbose_name='نوع دستاورد')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('icon', models.CharField(default='bi-trophy', max_length=50, verbose_name='آیکون')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاوردها',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='GamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='درباره من')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='community/avatars/', verbose_name='آواتار')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='community/banners/', verbose_name='بنر پروفایل')),
                ('city', models.CharField(blank=True, choices=[('tehran', 'تهران'), ('mashhad', 'مشهد'), ('isfahan', 'اصفهان'), ('shiraz', 'شیراز'), ('tabriz', 'تبریز'), ('ahvaz', 'اهواز'), ('karaj', 'کرج'), ('qom', 'قم'), ('rasht', 'رشت'), ('kermanshah', 'کرمانشاه'), ('urmia', 'ارومیه'), ('zahedan', 'زاهدان'), ('hamadan', 'همدان'), ('arak', 'اراک'), ('yazd', 'یزد'), ('other', 'سایر')], max_length=20, verbose_name='شهر')),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps4', 'PlayStation 4'), ('ps5', 'PlayStation 5'), ('xbox', 'Xbox'), ('switch', 'Nintendo Switch'), ('mobile', 'موبایل'), ('multi', 'چند پلتفرم')], default='pc', max_length=10, verbose_name='پلتفرم اصلی')),
                ('gaming_style', models.CharField(blank=True, choices=[('competitive', 'رقابتی / Competitive'), ('casual', 'تفریحی / Casual'), ('streamer', 'استریمر'), ('pro', 'حرفه\u200cای / Pro'), ('collector', 'کالکتور'), ('rpg_lover', 'دوستدار RPG')], max_length=20, verbose_name='سبک بازی')),
                ('rank', models.CharField(blank=True, choices=[('bronze', 'برنز'), ('silver', 'نقره'), ('gold', 'طلا'), ('platinum', 'پلاتینیوم'), ('diamond', 'الماس'), ('master', 'مستر'), ('grandmaster', 'گرندمستر'), ('challenger', 'چلنجر')], max_length=15, verbose_name='رنک')),
                ('favorite_games', models.TextField(blank=True, verbose_name='بازی\u200cهای مورد علاقه')),
                ('steam_id', models.CharField(blank=True, max_length=100, verbose_name='Steam ID')),
                ('psn_id', models.CharField(blank=True, max_length=100, verbose_name='PSN ID')),
                ('xbox_gamertag', models.CharField(blank=True, max_length=100, verbose_name='Xbox Gamertag')),
                ('total_hours_played', models.PositiveIntegerField(default=0, verbose_name='ساعت بازی')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='لول')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='امتیاز تجربه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل گیمر',
                'verbose_name_plural': 'پروفایل\u200cهای گیمران',
            },
        ),
        migrations.CreateModel(
            name='LFGPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, verbose_name='نام بازی')),
                ('game_mode', models.CharField(choices=[('ranked', 'رنکد'), ('normal', 'نرمال'), ('tournament', 'تورنمنت'), ('custom', 'کاستوم'), ('coop', 'Co-op')], default='normal', max_length=15, verbose_name='مود بازی')),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps4', 'PlayStation 4'), ('ps5', 'PlayStation 5'), ('xbox', 'Xbox'), ('switch', 'Nintendo Switch'), ('mobile', 'موبایل'), ('multi', 'چند پلتفرم')], max_length=10, verbose_name='پلتفرم')),
                ('skill_level', models.CharField(choices=[('beginner', 'تازه\u200cکار'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('pro', 'حرفه\u200cای'), ('any', 'همه سطوح')], default='any', max_length=15, verbose_name='سطح مهارت')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('max_players', models.PositiveSmallIntegerField(default=4, verbose_name='حداکثر بازیکن')),
                ('current_players', models.PositiveSmallIntegerField(default=1, verbose_name='بازیکنان فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lfg_posts', to=settings.AUTH_USER_MODEL, verbose_name='پست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'پست LFG',
                'verbose_name_plural': 'پست\u200cهای LFG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/posts/', verbose_name='تصویر')),
                ('post_type', models.CharField(choices=[('text', 'متن'), ('achievement', 'دستاورد'), ('lfg', 'جستجوی تیم'), ('highlight', 'هایلایت')], default='text', max_length=15, verbose_name='نوع پست')),
                ('game_tag', models.CharField(blank=True, max_length=100, verbose_name='تگ بازی')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='دنبال\u200cکننده')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL, verbose_name='دنبال\u200cشونده')),
            ],
            options={
                'verbose_name': 'دنبال کردن',
                'verbose_name_plural': 'دنبال کردن\u200cها',
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک\u200cها',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
