# Generated by Django 6.0.5 on 2026-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_hashtag_post_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community/posts/videos/', verbose_name='ویدیو'),
        ),
    ]
