# Generated by Django 6.0.5 on 2026-05-17 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_notifications_and_dm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=120, verbose_name='نام بازی')),
                ('status', models.CharField(choices=[('want', 'می\u200cخوام بازی کنم'), ('playing', 'دارم بازی می\u200cکنم'), ('completed', 'تموم کردم'), ('dropped', 'رها کردم')], default='want', max_length=12)),
                ('platform', models.CharField(blank=True, choices=[('pc', 'PC'), ('ps4', 'PlayStation 4'), ('ps5', 'PlayStation 5'), ('xbox', 'Xbox'), ('switch', 'Nintendo Switch'), ('mobile', 'موبایل'), ('multi', 'چند پلتفرم')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('cover_url', models.URLField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بک\u200cلاگ',
                'verbose_name_plural': 'بک\u200cلاگ\u200cها',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'game_name')},
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('fire', '🔥 خفن'), ('dead', '💀 GG'), ('tryhard', '😤 Tryhard'), ('legend', '👑 لجند'), ('ggez', '😂 GG EZ')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'واکنش',
                'verbose_name_plural': 'واکنش\u200cها',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
