# Generated by Django 6.0.5 on 2026-05-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='community_f_followe_e95289_idx',
            old_name='follow_follower_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='community_f_followi_5ff31f_idx',
            old_name='follow_following_idx',
        ),
        migrations.RenameIndex(
            model_name='gamebacklog',
            new_name='community_g_user_id_cca54b_idx',
            old_name='backlog_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gamebacklog',
            new_name='community_g_user_id_cf3f87_idx',
            old_name='backlog_user_fav_idx',
        ),
        migrations.RenameIndex(
            model_name='gamebacklog',
            new_name='community_g_user_id_aa738e_idx',
            old_name='backlog_user_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_author__c7cd0c_idx',
            old_name='post_author_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_is_publ_269832_idx',
            old_name='post_public_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='community_p_created_6febb2_idx',
            old_name='post_created_idx',
        ),
    ]
