# Generated by Django 6.0.5 on 2026-05-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_rename_follow_follower_idx_community_f_followe_e95289_idx_and_more'),
        ('dashboard', '0003_genre_to_genres_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebacklog',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlogs', to='dashboard.game', verbose_name='بازی'),
        ),
        migrations.AlterField(
            model_name='gamebacklog',
            name='game_name',
            field=models.CharField(max_length=200, verbose_name='نام بازی'),
        ),
    ]
