# Generated by Django 6.0.5 on 2026-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_rename_follow_follower_idx_community_f_followe_e95289_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='تأیید شده'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='تأیید شده'),
        ),
    ]
