# Generated by Django 6.0.5 on 2026-05-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_add_is_approved'),
        ('community', '0011_backlog_game_fk'),
    ]

    operations = [
    ]
