# Generated by Django 6.0.5 on 2026-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_merge_0011_add_is_approved_0011_backlog_game_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebacklog',
            name='game',
        ),
        migrations.AlterField(
            model_name='gamebacklog',
            name='game_name',
            field=models.CharField(max_length=120, verbose_name='نام بازی'),
        ),
    ]
