# Generated by Django 6.0.5 on 2026-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_notification_custom_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='notification',
            name='custom_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('mention', 'منشن'), ('admin', 'پیام ادمین')], max_length=10),
        ),
    ]
