# Generated by Django 6.0.1 on 2026-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_dm_attachments_block_pin_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='allow_dm',
            field=models.BooleanField(default=True, verbose_name='دریافت پیام مستقیم'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='پروفایل خصوصی'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بازدید'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='show_backlog',
            field=models.BooleanField(default=True, verbose_name='نمایش بک\u200cلاگ'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='نمایش ایمیل'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='show_last_seen',
            field=models.BooleanField(default=True, verbose_name='نمایش آخرین بازدید'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='show_online',
            field=models.BooleanField(default=True, verbose_name='نمایش آنلاین بودن'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='show_stats',
            field=models.BooleanField(default=True, verbose_name='نمایش آمار'),
        ),
    ]
