# Generated by Django 6.0.1 on 2026-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_alter_notification_notif_type_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='dm_followers_only',
            field=models.BooleanField(default=False, verbose_name='پیام فقط از دنبال\u200cکننده\u200cها'),
        ),
    ]
