# Generated by Django 6.0.1 on 2026-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_gamerprofile_dm_followers_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('follow_request', 'درخواست دنبال کردن'), ('follow_accepted', 'پذیرش دنبال کردن'), ('follow_rejected', 'رد دنبال کردن'), ('mention', 'منشن'), ('admin', 'پیام ادمین'), ('dm', 'پیام خصوصی')], max_length=15),
        ),
    ]
