# Generated by Django 6.0.1 on 2026-05-30 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_alter_notification_notif_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('challenge_type', models.CharField(choices=[('most_completed', 'بیشترین بازی تموم\u200cشده'), ('most_added', 'بیشترین بازی اضافه\u200cشده'), ('genre_week', 'ژانر هفته')], max_length=20)),
                ('genre_filter', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateTimeField(verbose_name='شروع')),
                ('end_date', models.DateTimeField(verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'چالش',
                'verbose_name_plural': 'چالش\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='pinned_game_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='بازی پین\u200cشده'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('started_playing', 'شروع به بازی کرد'), ('completed', 'تموم کرد'), ('added_to_list', 'اضافه کرد به لیستش'), ('dropped', 'رها کرد'), ('rated', 'امتیاز داد')], max_length=20)),
                ('game_name', models.CharField(max_length=120)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clubs/avatars/', verbose_name='آواتار گروه')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='clubs/banners/', verbose_name='بنر گروه')),
                ('genre_tag', models.CharField(blank=True, max_length=20, verbose_name='ژانر')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_posts', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.club')),
            ],
            options={
                'verbose_name': 'پست گروه',
                'verbose_name_plural': 'پست\u200cهای گروه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک'), ('admin', 'ادمین'), ('member', 'عضو')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو گروه',
                'verbose_name_plural': 'اعضای گروه',
                'unique_together': {('club', 'user')},
            },
        ),
    ]
