# Generated by Django 6.0.1 on 2026-05-30 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_add_groupchat_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='comments_enabled',
            field=models.BooleanField(default=False, verbose_name='کامنت فعال'),
        ),
        migrations.AddField(
            model_name='channel',
            name='linked_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_channel', to='community.groupchat', verbose_name='گروه متصل'),
        ),
        migrations.AddField(
            model_name='channel',
            name='reactions_enabled',
            field=models.BooleanField(default=True, verbose_name='ری\u200cاکشن فعال'),
        ),
        migrations.AddField(
            model_name='channel',
            name='require_approval',
            field=models.BooleanField(default=False, verbose_name='درخواست عضویت نیاز به تایید دارد'),
        ),
        migrations.AddField(
            model_name='channel',
            name='show_author',
            field=models.BooleanField(default=True, verbose_name='نمایش نویسنده پست'),
        ),
        migrations.CreateModel(
            name='ChannelJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='community.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست عضویت کانال',
                'unique_together': {('channel', 'user')},
            },
        ),
    ]
