# Generated by Django 6.0.1 on 2026-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_channel_comments_enabled_channel_linked_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
