# Generated by Django 6.0.5 on 2026-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_group_channel_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='location_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر/محله'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='show_location',
            field=models.BooleanField(default=False, verbose_name='نمایش موقعیت'),
        ),
    ]
