# Generated by Django 6.0.5 on 2026-06-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_gamerprofile_show_on_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
