# Generated by Django 6.0.5 on 2026-06-01 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_add_national_id_to_gamer_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='join_type',
            field=models.CharField(choices=[('open', 'مستقیم — هر کسی می\u200cتواند بپیوندد'), ('request', 'درخواستی — باید تأیید شود')], default='open', max_length=10, verbose_name='نوع پیوستن'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('follow_request', 'درخواست دنبال کردن'), ('follow_accepted', 'پذیرش دنبال کردن'), ('follow_rejected', 'رد دنبال کردن'), ('mention', 'منشن'), ('admin', 'پیام ادمین'), ('dm', 'پیام خصوصی'), ('lfg_join', 'پیوستن مستقیم LFG'), ('lfg_req', 'درخواست LFG'), ('lfg_ok', 'تأیید درخواست LFG'), ('lfg_no', 'رد درخواست LFG')], max_length=15),
        ),
        migrations.CreateModel(
            name='LFGJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='community.lfgpost', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lfg_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست پیوستن LFG',
                'verbose_name_plural': 'درخواست\u200cهای پیوستن LFG',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
