# Generated by Django 6.0.5 on 2026-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_groupchat_lfg_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_score', models.PositiveSmallIntegerField(default=1, help_text='هر پست چند امتیاز داشته باشد؟', verbose_name='امتیاز هر پست')),
                ('comment_score', models.PositiveSmallIntegerField(default=2, help_text='هر کامنت چند امتیاز داشته باشد؟', verbose_name='امتیاز هر کامنت')),
                ('active_day_score', models.PositiveSmallIntegerField(default=5, help_text='هر روزی که کاربر پست یا کامنت داشته باشد چند امتیاز دریافت می\u200cکند؟', verbose_name='امتیاز هر روز فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات امتیاز',
                'verbose_name_plural': 'تنظیمات امتیاز',
            },
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('fire', '🔥 خفن'), ('dead', '💀 GG'), ('tryhard', '😤 عصبانی'), ('legend', '👑 لجند'), ('ggez', '😂 GG EZ'), ('cry', '😢 گریه'), ('sob', '😭 اشک')], max_length=10),
        ),
    ]
