# Generated by Django 6.0.5 on 2026-06-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_score_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresettings',
            name='online_hour_score',
            field=models.PositiveSmallIntegerField(default=2, help_text='به ازای هر ساعت حضور در سایت چند امتیاز؟', verbose_name='امتیاز هر ساعت آنلاین'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سشن کاربر',
                'verbose_name_plural': 'سشن\u200cهای کاربران',
                'indexes': [models.Index(fields=['user', 'ended_at', '-last_activity'], name='community_u_user_id_08b27c_idx')],
            },
        ),
    ]
