# Generated by Django 6.0.5 on 2026-06-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_user_session_online_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], max_length=10, verbose_name='نوع دوره')),
                ('period_key', models.CharField(help_text='مثال: 2026-W22 | 2026-06 | 2026', max_length=20, verbose_name='کلید دوره')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='رتبه')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('online_secs', models.PositiveIntegerField(default=0)),
                ('snapshotted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lb_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اسنپ\u200cشات لیدربورد',
                'verbose_name_plural': 'اسنپ\u200cشات\u200cهای لیدربورد',
                'ordering': ['period_type', 'period_key', 'rank'],
                'unique_together': {('user', 'period_type', 'period_key')},
            },
        ),
    ]
