# Generated by Django 6.0.5 on 2026-06-03 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_leaderboard_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('follow_request', 'درخواست دنبال کردن'), ('follow_accepted', 'پذیرش دنبال کردن'), ('follow_rejected', 'رد دنبال کردن'), ('mention', 'منشن'), ('admin', 'پیام ادمین'), ('dm', 'پیام خصوصی'), ('lfg_join', 'پیوستن مستقیم LFG'), ('lfg_req', 'درخواست LFG'), ('lfg_ok', 'تأیید درخواست LFG'), ('lfg_no', 'رد درخواست LFG'), ('zarban', 'ضربان')], max_length=15),
        ),
        migrations.CreateModel(
            name='ZarbanWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='موجودی ضربان')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zarban_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول ضربان',
                'verbose_name_plural': 'کیف\u200cپول\u200cهای ضربان',
            },
        ),
        migrations.CreateModel(
            name='ZarbanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار')),
                ('tx_type', models.CharField(choices=[('credit', 'افزایش'), ('debit', 'کاهش')], max_length=10, verbose_name='نوع')),
                ('reason', models.CharField(blank=True, max_length=400, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zarban_given', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='community.zarbanwallet')),
            ],
            options={
                'verbose_name': 'تراکنش ضربان',
                'verbose_name_plural': 'تراکنش\u200cهای ضربان',
                'ordering': ['-created_at'],
            },
        ),
    ]
