# Generated by Django 6.0.1 on 2026-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_zarban_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoresettings',
            options={'verbose_name': 'تنظیمات ضربان', 'verbose_name_plural': 'تنظیمات ضربان'},
        ),
        migrations.AlterField(
            model_name='scoresettings',
            name='active_day_score',
            field=models.PositiveSmallIntegerField(default=5, help_text='هر روزی که کاربر پست یا کامنت داشته باشد چند ضربان دریافت می\u200cکند؟', verbose_name='ضربان هر روز فعال'),
        ),
        migrations.AlterField(
            model_name='scoresettings',
            name='comment_score',
            field=models.PositiveSmallIntegerField(default=2, help_text='هر کامنت چند ضربان داشته باشد؟', verbose_name='ضربان هر کامنت'),
        ),
        migrations.AlterField(
            model_name='scoresettings',
            name='online_hour_score',
            field=models.PositiveSmallIntegerField(default=2, help_text='به ازای هر ساعت حضور در سایت چند ضربان؟', verbose_name='ضربان هر ساعت آنلاین'),
        ),
        migrations.AlterField(
            model_name='scoresettings',
            name='post_score',
            field=models.PositiveSmallIntegerField(default=1, help_text='هر پست چند ضربان داشته باشد؟', verbose_name='ضربان هر پست'),
        ),
    ]
