# Generated by Django 6.0.1 on 2026-06-05 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_alter_scoresettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گردونه')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('daily_free_spins', models.PositiveSmallIntegerField(default=1, verbose_name='چرخش رایگان روزانه')),
                ('cost_zarban', models.PositiveIntegerField(default=50, verbose_name='هزینه چرخش اضافه (ضربان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گردونه شانس',
                'verbose_name_plural': 'گردونه\u200cهای شانس',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('follow_request', 'درخواست دنبال کردن'), ('follow_accepted', 'پذیرش دنبال کردن'), ('follow_rejected', 'رد دنبال کردن'), ('mention', 'منشن'), ('admin', 'پیام ادمین'), ('dm', 'پیام خصوصی'), ('lfg_join', 'پیوستن مستقیم LFG'), ('lfg_req', 'درخواست LFG'), ('lfg_ok', 'تأیید درخواست LFG'), ('lfg_no', 'رد درخواست LFG'), ('zarban', 'ضربان'), ('spin', 'گردونه شانس')], max_length=15),
        ),
        migrations.CreateModel(
            name='SpinWheelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آیتم')),
                ('probability', models.FloatField(default=10.0, verbose_name='درصد شانس')),
                ('reward_type', models.CharField(choices=[('zarban', 'ضربان 💜'), ('xp', 'XP ⚡'), ('spin', 'چرخش رایگان 🎰'), ('nothing', 'بدشانسی 💀')], default='nothing', max_length=10, verbose_name='نوع جایزه')),
                ('reward_amount', models.PositiveIntegerField(default=0, verbose_name='مقدار جایزه')),
                ('color', models.CharField(default='#6d28d9', max_length=7, verbose_name='رنگ خانه')),
                ('emoji', models.CharField(default='🎁', max_length=10, verbose_name='ایموجی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='community.spinwheel')),
            ],
            options={
                'verbose_name': 'آیتم گردونه',
                'verbose_name_plural': 'آیتم\u200cهای گردونه',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=True, verbose_name='رایگان بود؟')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='هزینه پرداختی')),
                ('spun_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان چرخش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_records', to='community.spinwheel', verbose_name='گردونه')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_records', to='community.spinwheelitem', verbose_name='آیتم برنده')),
            ],
            options={
                'verbose_name': 'رکورد چرخش',
                'verbose_name_plural': 'رکوردهای چرخش',
                'ordering': ['-spun_at'],
            },
        ),
    ]
