# Generated by Django 6.0.5 on 2026-06-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_spinwheel_cooldown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(db_index=True, verbose_name='شناسه بازی')),
                ('game_name', models.CharField(max_length=120, verbose_name='نام بازی')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز (1-10)')),
                ('body', models.TextField(max_length=1000, verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر بازی',
                'verbose_name_plural': 'نظرات بازی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game_id')},
            },
        ),
    ]
