# Generated by Django 6.0.5 on 2026-06-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_add_game_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='gamerprofile',
            name='xp',
        ),
    ]
