# Generated by Django 6.0.5 on 2026-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_remove_level_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinwheelitem',
            name='emoji',
            field=models.CharField(default='🎁', max_length=300, verbose_name='ایموجی'),
        ),
    ]
