# Generated by Django 6.0.5 on 2026-06-09 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_extend_spin_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('duration', models.CharField(choices=[('1_month', '۱ ماهه'), ('6_months', '۶ ماهه'), ('1_year', '۱ ساله')], max_length=20, verbose_name='مدت')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('features', models.TextField(blank=True, verbose_name='امکانات (هر خط یک امکان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پلن پریمیوم',
                'verbose_name_plural': 'پلن\u200cهای پریمیوم',
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('follow_request', 'درخواست دنبال کردن'), ('follow_accepted', 'پذیرش دنبال کردن'), ('follow_rejected', 'رد دنبال کردن'), ('mention', 'منشن'), ('admin', 'پیام ادمین'), ('dm', 'پیام خصوصی'), ('lfg_join', 'پیوستن مستقیم LFG'), ('lfg_req', 'درخواست LFG'), ('lfg_ok', 'تأیید درخواست LFG'), ('lfg_no', 'رد درخواست LFG'), ('zarban', 'ضربان'), ('spin', 'گردونه شانس'), ('profile_view', 'بازدید پروفایل')], max_length=15),
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع')),
                ('end_date', models.DateTimeField(verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_premiums', to=settings.AUTH_USER_MODEL, verbose_name='تخصیص\u200cدهنده')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.premiumplan', verbose_name='پلن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک پریمیوم',
                'verbose_name_plural': 'اشتراک\u200cهای پریمیوم',
                'ordering': ['-created_at'],
            },
        ),
    ]
