# Generated by Django 6.0.5 on 2026-06-09 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_add_premium_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'لایک پست'), ('comment', 'کامنت'), ('follow', 'فالو'), ('follow_request', 'درخواست دنبال کردن'), ('follow_accepted', 'پذیرش دنبال کردن'), ('follow_rejected', 'رد دنبال کردن'), ('mention', 'منشن'), ('admin', 'پیام ادمین'), ('dm', 'پیام خصوصی'), ('lfg_join', 'پیوستن مستقیم LFG'), ('lfg_req', 'درخواست LFG'), ('lfg_ok', 'تأیید درخواست LFG'), ('lfg_no', 'رد درخواست LFG'), ('zarban', 'ضربان'), ('spin', 'گردونه شانس'), ('profile_view', 'بازدید پروفایل'), ('view_digest', 'خلاصه بازدیدها')], max_length=15),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان بازدید')),
                ('notified', models.BooleanField(default=False, verbose_name='نوتیف ارسال شد')),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL, verbose_name='صاحب پروفایل')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_given', to=settings.AUTH_USER_MODEL, verbose_name='بازدیدکننده')),
            ],
            options={
                'verbose_name': 'بازدید پروفایل',
                'verbose_name_plural': 'بازدیدهای پروفایل',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_user', 'viewed_at'], name='community_p_viewed__506bca_idx'), models.Index(fields=['viewer', 'viewed_user'], name='community_p_viewer__be6c66_idx')],
            },
        ),
    ]
