# Generated by Django 6.0.5 on 2026-06-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_notification_sender_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boost_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انقضای بوست'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_boosted',
            field=models.BooleanField(default=False, verbose_name='بوست شده'),
        ),
    ]
