# Generated by Django 6.0.5 on 2026-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0042_post_boost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarbanwallet',
            name='online_zarban_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت\u200cهای جایزه\u200cداده\u200cشده'),
        ),
    ]
