# Generated by Django 6.0.5 on 2026-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0043_add_online_zarban_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='name_display',
            field=models.CharField(choices=[('full', 'نام و نام خانوادگی'), ('nickname', 'نام مستعار')], default='full', max_length=10, verbose_name='نمایش نام در پروفایل'),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام مستعار'),
        ),
    ]
