# Generated by Django 6.0.5 on 2026-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0044_gamerprofile_name_display_gamerprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='gaming_styles',
            field=models.JSONField(blank=True, default=list, verbose_name='سبک\u200cهای بازی'),
        ),
    ]
