# Generated by Django 6.0.5 on 2026-06-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0045_gamerprofile_gaming_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='بج آبی تیک — برای ادمین کلاب\u200cها/استریمرهای شناخته\u200cشده', verbose_name='تأیید\u200cشده'),
        ),
    ]
