# Generated by Django 6.0.5 on 2026-06-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0046_gamerprofile_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ماموریت')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('event', models.CharField(choices=[('login', 'ورود روزانه'), ('post', 'انتشار پست'), ('comment', 'ارسال کامنت'), ('follow', 'دنبال کردن گیمر'), ('lfg_join', 'پیوستن به LFG'), ('react', 'واکنش به پست')], max_length=20, verbose_name='رویداد')),
                ('target_count', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد هدف')),
                ('reward_zarban', models.PositiveIntegerField(default=10, verbose_name='جایزه (ضربان)')),
                ('icon', models.CharField(default='bi-check-circle-fill', max_length=40, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ماموریت روزانه',
                'verbose_name_plural': 'ماموریت\u200cهای روزانه',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('claimed', models.BooleanField(default=False, verbose_name='جایزه گرفته شده')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='community.dailymission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشرفت ماموریت',
                'verbose_name_plural': 'پیشرفت ماموریت\u200cها',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='community_d_user_id_ffcb0d_idx')],
                'unique_together': {('user', 'mission', 'date')},
            },
        ),
    ]
