# Generated by Django 6.0.5 on 2026-06-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0048_seed_daily_missions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(verbose_name='شماره روز در چرخه')),
                ('label', models.CharField(blank=True, max_length=60, verbose_name='عنوان روز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'روز ماموریت',
                'verbose_name_plural': 'روزهای چرخه\u200cی ماموریت',
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dailymission',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='community.missionday', verbose_name='روز چرخه (خالی = همیشگی)'),
        ),
    ]
