# Generated by Django 6.0.5 on 2026-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0049_missionday_dailymission_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='contact',
            field=models.CharField(blank=True, max_length=120, verbose_name='دیسکورد / آیدی بازی'),
        ),
    ]
