# Generated by Django 6.0.5 on 2026-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0050_lfgpost_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ach_type', models.CharField(max_length=50, unique=True, verbose_name='کد یکتا')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('icon', models.CharField(default='bi-trophy', max_length=60, verbose_name='آیکون Bootstrap')),
                ('reward_zarban', models.PositiveIntegerField(default=0, verbose_name='جایزه ضربان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تعریف دستاورد',
                'verbose_name_plural': 'تعاریف دستاوردها',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('first_post', 'اولین پست'), ('first_follow', 'اولین فالو'), ('popular_post', 'پست پرلایک'), ('veteran', 'کهنه\u200cکار'), ('social', 'اجتماعی'), ('tournament_win', 'برنده تورنمنت'), ('custom', 'سفارشی')], max_length=50, verbose_name='نوع دستاورد'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='bi-trophy', max_length=60, verbose_name='آیکون'),
        ),
    ]
