# Generated by Django 6.0.5 on 2026-05-25 07:45

from django.db import migrations, models


def genre_to_genres(apps, schema_editor):
    Game = apps.get_model('dashboard', 'Game')
    for game in Game.objects.all():
        old_genre = game.genre if hasattr(game, 'genre') else ''
        game.genres = [old_genre] if old_genre else []
        game.save(update_fields=['genres'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_game_is_active'),
    ]

    operations = [
        # Step 1: add new field while old one still exists
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.JSONField(default=list, verbose_name='ژانرها'),
        ),
        # Step 2: migrate data
        migrations.RunPython(genre_to_genres, migrations.RunPython.noop),
        # Step 3: remove old field
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
