# Generated by Django 6.0.1 on 2026-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_genre_to_genres_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتیاز متاکریتیک'),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, verbose_name='اسکرین\u200cشات\u200cها'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_price',
            field=models.CharField(blank=True, max_length=50, verbose_name='قیمت استیم'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_url',
            field=models.URLField(blank=True, verbose_name='لینک استیم'),
        ),
    ]
