# Generated by Django 6.0.5 on 2026-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_game_metacritic_game_screenshots_game_steam_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='آنلاین/چندنفره'),
        ),
    ]
