# Generated by Django 6.0.5 on 2026-06-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_game_is_crack_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='پرطرفدار'),
        ),
    ]
