# Generated by Django 6.0.5 on 2026-06-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_is_popular_to_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام بازی'),
        ),
    ]
