# Generated by Django 6.0.5 on 2026-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_unique_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='auto_imported',
            field=models.BooleanField(default=False, verbose_name='ایمپورت خودکار از استیم'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_appid',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Steam AppID'),
        ),
    ]
