# Generated by Django 6.0.5 on 2026-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_game_auto_imported_game_steam_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_fa',
            field=models.CharField(blank=True, help_text='اسم\u200cهای فارسی/فینگلیش که کاربر ممکنه باهاشون سرچ کنه. نمایش داده نمی\u200cشه.', max_length=300, verbose_name='نام/معادل فارسی (فقط برای جستجو)'),
        ),
    ]
