# Generated by Django 6.0.1 on 2026-01-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='تعداد جلسات')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='درآمد کل')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ساعت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گزارش روزانه',
                'verbose_name_plural': 'گزارش\u200cهای روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بازی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='ژانر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='تصویر بازی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='شماره دستگاه')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('pc', 'کامپیوتر'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('xbox', 'Xbox'), ('vr', 'VR')], default='pc', max_length=20, verbose_name='نوع دستگاه')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت ساعتی (تومان)')),
                ('status', models.CharField(choices=[('available', 'آزاد'), ('occupied', 'در حال استفاده'), ('maintenance', 'در حال تعمیر')], default='available', max_length=20, verbose_name='وضعیت')),
                ('specs', models.TextField(blank=True, verbose_name='مشخصات فنی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('games', models.ManyToManyField(blank=True, to='gamenet.game', verbose_name='بازی\u200cهای موجود')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه\u200cها',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن مشتری')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'پایان یافته'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت ساعتی')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه کل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gamenet.device', verbose_name='دستگاه')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مسابقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('entry_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ورودی')),
                ('prize_pool', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جایزه کل')),
                ('max_participants', models.PositiveIntegerField(default=16, verbose_name='حداکثر شرکت\u200cکنندگان')),
                ('status', models.CharField(choices=[('upcoming', 'در انتظار'), ('ongoing', 'در حال برگزاری'), ('completed', 'پایان یافته'), ('cancelled', 'لغو شده')], default='upcoming', max_length=20, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournaments/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamenet.game', verbose_name='بازی')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('gamer_tag', models.CharField(blank=True, max_length=50, verbose_name='آیدی گیمری')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamenet.tournament', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده',
                'verbose_name_plural': 'شرکت\u200cکنندگان',
                'unique_together': {('tournament', 'phone')},
            },
        ),
    ]
