# Generated by Django 6.0.1 on 2026-01-30 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت (روز)')),
                ('max_devices', models.PositiveIntegerField(default=10, verbose_name='حداکثر دستگاه')),
                ('max_tournaments', models.PositiveIntegerField(default=5, verbose_name='حداکثر مسابقه در ماه')),
                ('features', models.TextField(blank=True, verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.PositiveIntegerField(verbose_name='شماره دستگاه'),
        ),
        migrations.CreateModel(
            name='GameNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام گیم\u200cنت')),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gamenets/logos/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamenets', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'گیم\u200cنت',
                'verbose_name_plural': 'گیم\u200cنت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='gamenet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gamenet.gamenet', verbose_name='گیم\u200cنت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='gamenet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gamenet.gamenet', verbose_name='گیم\u200cنت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gamenet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamenet.gamenet', verbose_name='گیم\u200cنت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='gamenet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='gamenet.gamenet', verbose_name='گیم\u200cنت'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('gamenet', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('gamenet', 'number')},
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('is_active', models.BooleanField(default=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gamenet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gamenet.gamenet', verbose_name='گیم\u200cنت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamenet.subscriptionplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
