# Generated by Django 6.0.1 on 2026-01-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0002_subscriptionplan_alter_dailyreport_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
