# Generated by Django 6.0.1 on 2026-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0003_remove_session_status_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenet',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='gamenet',
            name='extra_controller_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت دسته اضافی (تومان/ساعت)'),
        ),
        migrations.AddField(
            model_name='session',
            name='extra_controller_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت دسته اضافی (تومان/ساعت)'),
        ),
        migrations.AddField(
            model_name='session',
            name='extra_controllers',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دسته اضافی'),
        ),
    ]
