# Generated by Django 6.0.1 on 2026-02-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0004_gamenet_description_gamenet_extra_controller_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gamenets/gallery/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gamenet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gamenet.gamenet', verbose_name='گیم\u200cنت')),
            ],
            options={
                'verbose_name': 'تصویر گیم\u200cنت',
                'verbose_name_plural': 'تصاویر گیم\u200cنت',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
