# Generated by Django 6.0.1 on 2026-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0006_order_product_orderitem_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='آیکون'),
        ),
    ]
