# Generated by Django 6.0.1 on 2026-02-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0008_product_prices_and_orderitem_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenet',
            name='ps4_controller_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت دسته PS4 اضافی (تومان/ساعت)'),
        ),
        migrations.AddField(
            model_name='gamenet',
            name='ps5_controller_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت دسته PS5 اضافی (تومان/ساعت)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='قیمت خرید (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='قیمت عرضه (تومان)'),
        ),
    ]
