# Generated by Django 6.0.1 on 2026-02-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0011_tournament_end_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion_in_tournaments', to='gamenet.tournamentparticipant', verbose_name='قهرمان'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_open',
            field=models.BooleanField(default=True, verbose_name='ثبت\u200cنام باز است'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='شماره دور')),
                ('match_number', models.PositiveIntegerField(verbose_name='شماره بازی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'پایان یافته'), ('bye', 'استراحت')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_participant1', to='gamenet.tournamentparticipant', verbose_name='شرکت\u200cکننده 1')),
                ('participant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_participant2', to='gamenet.tournamentparticipant', verbose_name='شرکت\u200cکننده 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gamenet.tournament', verbose_name='مسابقه')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournament_matches', to='gamenet.tournamentparticipant', verbose_name='برنده')),
            ],
            options={
                'verbose_name': 'بازی تورنومنت',
                'verbose_name_plural': 'بازی\u200cهای تورنومنت',
                'ordering': ['round_number', 'match_number', 'id'],
                'unique_together': {('tournament', 'round_number', 'match_number')},
            },
        ),
    ]
