# Generated by Django 6.0.1 on 2026-02-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0012_tournament_champion_tournament_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='show_participants_public',
            field=models.BooleanField(default=True, verbose_name='نمایش عمومی شرکت\u200cکنندگان'),
        ),
    ]
