# Generated by Django 6.0.1 on 2026-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenet', '0013_tournament_show_participants_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_participants/', verbose_name='تصویر'),
        ),
    ]
