from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.feed, name='feed'),
    path('search/', views.search_gamers, name='search'),
    path('lfg/', views.lfg_board, name='lfg'),
    path('lfg/create/', views.create_lfg, name='create_lfg'),
    path('lfg/<int:post_id>/join/', views.join_lfg, name='lfg_join'),
    path('lfg/<int:post_id>/delete-party-group/', views.delete_party_group, name='delete_party_group'),
    path('lfg/join-requests/<int:req_id>/respond/', views.respond_lfg_join, name='lfg_join_respond'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('post/create/', views.create_post, name='create_post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('post/<int:post_id>/interactions/', views.post_interactions, name='post_interactions'),
    path('post/<int:post_id>/likes/', views.post_likes_list, name='post_likes_list'),
    path('post/<int:post_id>/comments-json/', views.post_comments_list, name='post_comments_list'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/update-banner/', views.update_banner, name='update_banner'),
    path('settings/', views.user_settings, name='settings'),
    path('profile/me/', views.my_profile_dashboard, name='my_profile'),
    path('profile/<str:username>/', views.gamer_profile, name='profile'),
    path('profile/<str:username>/follow-list/', views.profile_follow_list, name='profile_follow_list'),
    path('follow/<str:username>/', views.toggle_follow, name='toggle_follow'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('post/<int:post_id>/boost/', views.boost_post, name='boost_post'),
    path('gaming/connect/', views.connect_gaming_account, name='connect_gaming'),
    path('gaming/disconnect/', views.disconnect_gaming_account, name='disconnect_gaming'),
    path('gaming/<int:pk>/toggle-visibility/', views.toggle_gaming_account_visibility, name='toggle_gaming_visibility'),
    path('gaming/steam/login/', views.steam_login, name='steam_login'),
    path('gaming/steam/callback/', views.steam_callback, name='steam_callback'),
    path('gaming/steam/import-backlog/', views.steam_import_backlog, name='steam_import_backlog'),
    path('post/new/', views.create_post_page, name='create_post_page'),
    path('api/hashtags/', views.hashtag_suggest, name='hashtag_suggest'),
    path('api/link-preview/', views.link_preview, name='link_preview'),
    path('hashtag/<str:tag_name>/', views.hashtag_feed, name='hashtag_feed'),
    # Reactions
    path('post/<int:post_id>/react/', views.react_post, name='react_post'),
    path('post/<int:post_id>/reactions/', views.get_post_reactions, name='post_reactions'),
    # Steam
    path('steam/fetch/', views.steam_fetch, name='steam_fetch'),
    path('steam/search/', views.steam_search, name='steam_search'),
    # Backlog
    path('backlog/add/', views.backlog_add, name='backlog_add'),
    path('backlog/<int:item_id>/update/', views.backlog_update, name='backlog_update'),
    path('backlog/<int:item_id>/remove/', views.backlog_remove, name='backlog_remove'),
    path('backlog/<int:item_id>/favorite/', views.backlog_toggle_favorite, name='backlog_favorite'),
    path('backlog/<str:username>/', views.backlog_list, name='backlog_list'),
    path('games/', views.games_ranking, name='games_ranking'),
    path('games/<int:game_id>/', views.game_detail, name='game_detail'),
    path('games/<int:game_id>/rate/', views.rate_game, name='rate_game'),
    path('games/<int:game_id>/reviews/add/', views.add_game_review, name='add_game_review'),
    path('games/<int:game_id>/reviews/<int:review_id>/delete/', views.delete_game_review, name='delete_game_review'),
    # Activity Feed
    path('activity/', views.activity_feed, name='activity_feed'),
    # Profile extras
    path('profile/set-pinned-game/', views.set_pinned_game, name='set_pinned_game'),
    # Challenges
    path('challenges/', views.challenges_page, name='challenges'),
    # ماموریت‌های روزانه
    path('missions/', views.daily_missions, name='daily_missions'),
    path('missions/<int:mission_id>/claim/', views.claim_mission, name='claim_mission'),
    # Clubs
    path('clubs/', views.clubs_list, name='clubs_list'),
    path('clubs/create/', views.create_club, name='create_club'),
    path('clubs/<slug:slug>/', views.club_detail, name='club_detail'),
    path('clubs/<slug:slug>/join/', views.join_club, name='join_club'),
    path('clubs/<slug:slug>/leave/', views.leave_club, name='leave_club'),
    path('clubs/<slug:slug>/post/', views.club_post, name='club_post'),
    # Follow Requests
    path('follow-requests/', views.manage_follow_requests, name='follow_requests'),
    path('follow-requests/<int:request_id>/respond/', views.respond_follow_request, name='respond_follow_request'),
    # Notifications
    path('notifications/', views.notifications_list, name='notifications'),
    path('notifications/mark-all-read/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('api/notifications/count/', views.notifications_count, name='notifications_count'),
    path('api/notifications/recent/', views.notifications_recent, name='notifications_recent'),
    path('search/global/', views.global_search, name='global_search'),
    path('onboarding/', views.onboarding, name='onboarding'),
    # Direct Messages
    path('inbox/', views.inbox, name='inbox'),
    path('dm/<str:username>/', views.conversation, name='conversation'),
    path('dm/<str:username>/send/', views.send_message_ajax, name='send_message'),
    path('api/inbox/count/', views.inbox_unread_count, name='inbox_count'),
    path('heartbeat/', views.heartbeat, name='heartbeat'),
    path('api/dm-list/', views.dm_list_api, name='dm_list_api'),
    path('api/game-search/', views.game_search_api, name='game_search_api'),
    path('dm/<str:username>/mark-read/', views.mark_conversation_read, name='mark_conversation_read'),
    path('dm/<str:username>/poll/', views.conversation_poll, name='conversation_poll'),
    # Block / Pin / Mute
    path('block/<str:username>/', views.toggle_block, name='toggle_block'),
    path('pin-conv/<int:conv_id>/', views.toggle_pin_conversation, name='pin_conversation'),
    path('mute-conv/<int:conv_id>/', views.toggle_mute_conversation, name='mute_conversation'),
    # Group Chat
    path('groups/create/', views.create_group, name='create_group'),
    path('groups/<int:group_id>/', views.group_chat, name='group_chat'),
    path('groups/<int:group_id>/send/', views.group_send_message, name='group_send_message'),
    path('groups/<int:group_id>/poll/', views.group_poll_messages, name='group_poll_messages'),
    path('groups/<int:group_id>/pin/', views.group_pin, name='group_pin'),
    path('groups/<int:group_id>/mute/', views.group_mute, name='group_mute'),
    path('groups/<int:group_id>/leave/', views.group_leave, name='group_leave'),
    path('groups/<int:group_id>/add-member/', views.group_add_member, name='group_add_member'),
    path('groups/<int:group_id>/add-admin/<str:username>/', views.group_add_admin, name='group_add_admin'),
    path('groups/<int:group_id>/remove-admin/<str:username>/', views.group_remove_admin, name='group_remove_admin'),
    path('groups/<int:group_id>/remove-member/<str:username>/', views.group_remove_member, name='group_remove_member'),
    # Channels
    path('channels/create/', views.create_channel, name='create_channel'),
    path('channels/post/<int:post_id>/react/', views.channel_react, name='channel_react'),
    path('channels/<str:channel_username>/', views.channel_view, name='channel_view'),
    path('channels/<str:channel_username>/subscribe/', views.channel_subscribe, name='channel_subscribe'),
    path('channels/<str:channel_username>/post/', views.channel_post, name='channel_post'),
    path('channels/<str:channel_username>/pin/', views.channel_pin, name='channel_pin'),
    path('channels/<str:channel_username>/mute/', views.channel_mute, name='channel_mute'),
    path('channels/<str:channel_username>/settings/', views.channel_settings, name='channel_settings'),
    path('channels/<str:channel_username>/add-admin/<str:username>/', views.channel_add_admin, name='channel_add_admin'),
    path('channels/<str:channel_username>/remove-admin/<str:username>/', views.channel_remove_admin, name='channel_remove_admin'),
    # Gamer Finder
    path('gamer-finder/', views.gamer_finder_page, name='gamer_finder'),
    path('api/gamer-finder/search/', views.gamer_finder_search, name='gamer_finder_search'),
    path('api/location/save/', views.save_location, name='save_location'),
    # گردونه شانس
    path('spin/', views.spin_list, name='spin_list'),
    path('spin/<int:wheel_id>/', views.spin_detail, name='spin_detail'),
    path('spin/<int:wheel_id>/go/', views.spin_go, name='spin_go'),
    # بازدیدکنندگان پروفایل
    path('who-viewed-me/', views.who_viewed_me, name='who_viewed_me'),
    # آمارها (پریمیوم)
    path('stats/', views.profile_stats, name='profile_stats'),
    # پریمیوم (پابلیک)
    path('premium/', views.premium_info, name='premium_info'),
]
